name: release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: yarn install
      - run: yarn build
      - run: rm .gitignore
      - run: |
          git config --global user.name 'masarakki'
          git config --global user.email 'masaki182@gmail.com'
      - run: git add .
      - run: git commit -m 'release'
      - run: git tag --force v`cat VERSION`
      - run: git push --tags --force
