name: release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: corepack enable
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
      - run: yarn install
      - run: yarn build
      - run: rm .gitignore
      - run: |
          git config --global user.name 'masarakki'
          git config --global user.email 'masaki182@gmail.com'
      - run: git add .
      - run: git commit -m 'release'
      - run: git tag --force v`cat VERSION`
      - run: git push --tags --force
